../../verilog/tb/configure.sv
../../verilog/constants.sv
../../verilog/functions.sv
../../verilog/wires.sv
../../verilog/bit_alu.sv
../../verilog/bit_clmul.sv
../../verilog/alu.sv
../../verilog/agu.sv
../../verilog/bcu.sv
../../verilog/lsu.sv
../../verilog/csr_alu.sv
../../verilog/mul.sv
../../verilog/div.sv
../../verilog/decoder.sv
../../verilog/register.sv
../../verilog/csr.sv
../../verilog/compress.sv
../../verilog/prefetch.sv
../../verilog/writebuffer.sv
../../verilog/forwarding.sv
../../verilog/fetch_stage.sv
../../verilog/decode_stage.sv
../../verilog/execute_stage.sv
../../verilog/memory_stage.sv
../../verilog/writeback_stage.sv
../../verilog/clint.sv
../../verilog/itim.sv
../../verilog/dtim.sv
../../verilog/cpu.sv
../../verilog/tb/bram.sv
../../verilog/tb/print.sv
../../verilog/tb/soc.sv
